//----------------------------------------------------------------------------------------------------
// Image — <img> element whose src may be a URL, binary data, or a Promise of either
// Binary sources become object URLs revoked when the unit is destroyed, so callers can display fetched /
// generated bytes without managing URL lifetime.
//----------------------------------------------------------------------------------------------------

import { xnew } from '../../core/xnew';

type ImageSource = string | Blob | ArrayBuffer | ArrayBufferView<ArrayBuffer>;

export function Image(unit: xnew.Unit,
    { src, className = '', style = '', ...others }:
    { src: ImageSource | Promise<ImageSource>, className?: string, style?: string, [key: string]: any }
) {
    const css = xnew.css('base', {
        container: `
        `,
    });

    xnew.nest({ tag: 'img', className: `${css.container} ${className}`, style, ...others });
    const element = unit.current as HTMLImageElement;

    let objectURL: string | null = null;
    function apply(value: ImageSource): void {
        if (typeof value === 'string') {
            element.src = value;
        } else {
            objectURL = URL.createObjectURL(value instanceof Blob ? value : new Blob([value]));
            element.src = objectURL;
        }
    }
    if (src instanceof Promise) {
        xnew.promise(src).then(apply);
    } else {
        apply(src);
    }

    unit.on('destroy', () => {
        if (objectURL !== null) {
            URL.revokeObjectURL(objectURL);
        }
    });
}
