//----------------------------------------------------------------------------------------------------
// Image — <img> element whose src may be a URL, binary data, or a Promise of either
// Binary sources become object URLs revoked on finalize, so callers can display fetched /
// generated bytes without managing URL lifetime.
//----------------------------------------------------------------------------------------------------

import { xnew } from '../../core/xnew';
import { Container } from './Container';
import { Design } from '../design';

type ImageSource = string | Blob | ArrayBuffer | ArrayBufferView<ArrayBuffer>;

export function Image(unit: xnew.Unit,
    { src, className = '', style = '', designs = {}, ...others }:
    { src: ImageSource | Promise<ImageSource>, className?: string, style?: string, designs?: { image?: Design }, [key: string]: any }
) {
    xnew.extend(Container, {
        className, style,
    });

    const css = xnew.css({
        image: {
            layer: 'base',
            body: `
                box-sizing: border-box; display: block; width: 100%; height: 100%;
            `,
        },
    });

    xnew.nest({ tag: 'img', className: `${css.image} ${designs.image?.className ?? ''}`, style: designs.image?.style, ...others });
    const element = unit.element as HTMLImageElement;

    let objectURL: string | null = null;
    function apply(value: ImageSource): void {
        if (typeof value === 'string') {
            element.src = value;
        } else {
            objectURL = URL.createObjectURL(value instanceof Blob ? value : new Blob([value]));
            element.src = objectURL;
        }
    }
    if (src instanceof Promise) {
        xnew.promise(src).then(apply);
    } else {
        apply(src);
    }

    unit.on('finalize', () => {
        if (objectURL !== null) {
            URL.revokeObjectURL(objectURL);
        }
    });
}
