// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: './examples'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'manual',
      link: {
        type: 'generated-index',
        title: 'manual',
        description: 'Learn about the most important xnew concepts!',
        slug: '/manual',
      },
      items: [
        'manual/getstarted',
        {
          type: 'category',
          label: 'core',
          collapsed: false,
          link: {
            type: 'generated-index',
            title: 'core',
            slug: '/manual/core',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'manual/core',
            },
          ],
        },
        {
          type: 'category',
          label: 'basics',
          collapsed: false,
          link: {
            type: 'generated-index',
            title: 'basics',
            slug: '/manual/basics',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'manual/basics',
            },
          ],
        },
        {
          type: 'category',
          label: 'addons',
          collapsed: false,
          link: {
            type: 'generated-index',
            title: 'addons',
            slug: '/manual/addons',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'manual/addons',
            },
          ],
        },
      ]
    }
  ],
  examplesSidebar: [
    {
      type: 'category',
      label: 'examples',
      link: {
        type: 'generated-index',
        title: 'examples',
        description: 'varaius xnew examples!',
        slug: '/examples',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'examples',
        },
      ],
    },
  ],
};

export default sidebars;
