//----------------------------------------------------------------------------------------------------
// Element — basic HTML element components
//
// Image nests an <img> whose src may be a URL string, binary data, or a Promise of either — binary
// sources become object URLs revoked on finalize, so callers can display fetched / generated bytes
// without managing URL lifetime.
//
// - Image : component({ src, className, style }) — src: string | Blob | ArrayBuffer(View) | Promise
//
// Example: xnew(xbasics.Image, { src: './background.jpg', className: 'absolute inset-0 size-full', style: 'object-fit: cover;' });
//----------------------------------------------------------------------------------------------------

import { xnew } from '../core/xnew';
import { Unit } from '../core/unit';

type ImageSource = string | Blob | ArrayBuffer | ArrayBufferView<ArrayBuffer>;

export function Image(unit: Unit,
    { src, className = '', style = '' }:
    { src: ImageSource | Promise<ImageSource>, className?: string, style?: string }
) {
    xnew.nest(`<img class="${className}" style="${style}">`);
    const element = unit.element as HTMLImageElement;

    let objectURL: string | null = null;
    function apply(value: ImageSource): void {
        if (typeof value === 'string') {
            element.src = value;
        } else {
            objectURL = URL.createObjectURL(value instanceof Blob ? value : new Blob([value]));
            element.src = objectURL;
        }
    }
    if (src instanceof Promise) {
        xnew.promise(src).then(apply);
    } else {
        apply(src);
    }

    unit.on('finalize', () => {
        if (objectURL !== null) {
            URL.revokeObjectURL(objectURL);
        }
    });
}
